global:
  # Intervalo con el que Prometheus rastrea por defecto.
  scrape_interval: 15s 

scrape_configs:
  # Configuramos Prometheus para que se monitoree a sí mismo.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Configuramos el rastreo para tu aplicación Spring Boot.
  - job_name: 'pixelplayback-backend'
    # Esta configuración es CRÍTICA. Usa 'host.docker.internal' para
    # que Docker pueda acceder a un servicio que está corriendo en tu máquina (el host).
    # Spring Boot expone las métricas en /actuator/prometheus
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'pixelplayback'